# 麒麟量化系统配置文件示例
# 将此文件复制为 config.yaml 并填入实际配置

# 数据源配置
data:
  # Tushare配置
  tushare:
    token: "your_tushare_token_here"  # 在 https://tushare.pro 申请
    
  # AkShare配置（无需token）
  akshare:
    enabled: true
    
  # 缓存配置
  cache:
    # Redis配置（可选）
    redis_url: "redis://localhost:6379/0"
    # 缓存过期时间（秒）
    ttl: 300
    
  # 数据存储路径
  storage:
    data_dir: "data"
    cache_dir: "cache"

# 交易配置
trading:
  # 历史数据回看天数
  lookback_days: 30
  
  # 实时数据更新间隔（秒）
  realtime_interval: 5
  
  # 交易时段
  trading_hours:
    morning_start: "09:30"
    morning_end: "11:30"
    afternoon_start: "13:00"
    afternoon_end: "15:00"

# Agent配置
agents:
  # 各Agent权重配置
  weights:
    AuctionGameAgent: 0.15
    MarketEcologyAgent: 0.15
    EmotionalCycleAgent: 0.10
    FundFlowAgent: 0.15
    EventDrivenAgent: 0.10
    TechnicalPatternAgent: 0.10
    MicrostructureAgent: 0.10
    SentimentAnalysisAgent: 0.10
    RiskAssessmentAgent: 0.05
  
  # Agent评分阈值
  thresholds:
    buy: 70
    sell: 30
    strong_buy: 85
    strong_sell: 15

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/qilin.log"
  max_size: "10MB"
  backup_count: 5

# API配置
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false

# 数据库配置（可选）
database:
  url: "postgresql://user:password@localhost/qilin_db"
  pool_size: 10
  echo: false

# 通知配置（可选）
notification:
  # 邮件通知
  email:
    enabled: false
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "your_email@gmail.com"
    password: "your_password"
    recipients:
      - "recipient@example.com"
  
  # 微信通知（通过企业微信）
  wechat:
    enabled: false
    webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"

# 风控配置
risk:
  # 最大持仓数
  max_positions: 10
  
  # 单只股票最大仓位
  max_position_size: 0.2
  
  # 止损比例
  stop_loss: 0.08
  
  # 止盈比例
  take_profit: 0.20
  
  # 最大回撤限制
  max_drawdown: 0.15

# 策略配置
strategy:
  # 策略类型
  type: "multi_factor"
  
  # 调仓频率
  rebalance_frequency: "daily"
  
  # 选股数量
  stock_pool_size: 50
  
  # 是否开启回测
  backtest:
    enabled: true
    start_date: "2023-01-01"
    end_date: "2024-01-01"
    initial_capital: 1000000
    commission: 0.0003
    slippage: 0.001