# 麒麟量化系统配置文件示例
# 将此文件复制为 config.yaml 并填入实际配置

# 数据源配置
data:
  # Tushare配置
  tushare:
    token: "your_tushare_token_here"  # 在 https://tushare.pro 申请
    
  # AkShare配置（无需token）
  akshare:
    enabled: true
    
  # 缓存配置
  cache:
    # Redis配置（可选）
    redis_url: "redis://localhost:6379/0"
    # 缓存过期时间（秒）
    ttl: 300
    
  # 数据存储路径
  storage:
    data_dir: "data"
    cache_dir: "cache"

# 交易配置
trading:
  # 历史数据回看天数
  lookback_days: 30
  
  # 实时数据更新间隔（秒）
  realtime_interval: 5
  
  # 交易时段
  trading_hours:
    morning_start: "09:30"
    morning_end: "11:30"
    afternoon_start: "13:00"
    afternoon_end: "15:00"

# v2.1 核心升级：市场风格元帅 (Market Regime Marshal)
market_regime:
  # 模式一：游资混战期 (短线博弈天堂)
  hot_money_chaos:
    agent_weights: # 重点是生态、竞价和情绪
      ZTQualityAgent: 0.15
      LeaderAgent: 0.20
      AuctionAgent: 0.20
      MoneyFlowAgent: 0.15
      EmotionAgent: 0.15
      TechnicalAgent: 0.05
      RiskAgent: -0.10 # 风险作为扣分项
    risk_parameters: # 敢于承担风险
      stop_loss: -0.07
      take_profit: 0.20
      max_position_size: 0.3
    strategy_parameters:
      holding_period: 2 # 天, 持股周期短

  # 模式二：机构趋势期 (价值投资者的春天)
  institutional_trending:
    agent_weights: # 重点是基本面、资金和技术趋势
      ZTQualityAgent: 0.05
      LeaderAgent: 0.10
      AuctionAgent: 0.05
      MoneyFlowAgent: 0.30 # 资金流向权重最高
      EmotionAgent: 0.05
      TechnicalAgent: 0.25 # 技术趋势很重要
      RiskAgent: -0.20 # 趋势市更怕黑天鹅
    risk_parameters: # 拉长止损，放大止盈
      stop_loss: -0.10
      take_profit: 0.30
      max_position_size: 0.2
    strategy_parameters:
      holding_period: 10 # 天, 持股周期长

  # 模式三：熊市恐慌期 (现金为王)
  bear_market_panic:
    agent_weights: # 所有进攻项权重降低，风险权重提高
      ZTQualityAgent: 0.05
      LeaderAgent: 0.05
      AuctionAgent: 0.05
      MoneyFlowAgent: 0.10
      EmotionAgent: 0.05
      TechnicalAgent: 0.10
      RiskAgent: -0.60 # 风险一票否决
    risk_parameters: # 极度严格的风控
      stop_loss: -0.03
      take_profit: 0.05
      max_position_size: 0.1
    strategy_parameters:
      holding_period: 1 # 天，只做日内或隔日套利

  # 模式四：震荡迷茫期 (多看少动)
  volatile_uncertainty:
    agent_weights: # 权重分散，没有明显重点
      ZTQualityAgent: 0.10
      LeaderAgent: 0.10
      AuctionAgent: 0.10
      MoneyFlowAgent: 0.10
      EmotionAgent: 0.10
      TechnicalAgent: 0.10
      RiskAgent: -0.40
    risk_parameters: # 降低参与度
      stop_loss: -0.05
      take_profit: 0.08
      max_position_size: 0.15
    strategy_parameters:
      holding_period: 2

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/qilin.log"
  max_size: "10MB"
  backup_count: 5

# v2.1 核心升级: 可解释性与归因分析
explainability:
  enabled: true # 是否开启可解释性分析
  # 决策归因可视化
  decision_trace:
    enabled: true
    max_depth: 3 # 下钻深度
  # 交易后归因分析
  post_trade_attribution:
    enabled: true
    beta_benchmark: "sh000300" # Alpha/Beta分析的基准指数

# API配置
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false

# 数据库配置（可选）
database:
  url: "postgresql://user:password@localhost/qilin_db"
  pool_size: 10
  echo: false

# 通知配置（可选）
notification:
  # 邮件通知
  email:
    enabled: false
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "your_email@gmail.com"
    password: "your_password"
    recipients:
      - "recipient@example.com"
  
  # 微信通知（通过企业微信）
  wechat:
    enabled: false
    webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"

# 风控配置 (v2.1 升级: 此处为默认值，实际风控由 market_regime 动态决定)
risk:
  # 最大持仓数
  max_positions: 5
  
  # 单只股票最大仓位
  max_position_size: 0.2
  
  # 止损比例
  stop_loss: 0.08
  
  # 止盈比例
  take_profit: 0.20
  
  # 最大回撤限制
  max_drawdown: 0.15

# 策略配置
strategy:
  # 策略类型
  type: "multi_factor"
  
  # 调仓频率
  rebalance_frequency: "daily"
  
  # 选股数量
  stock_pool_size: 50
  
  # 是否开启回测
  backtest:
    enabled: true
    start_date: "2023-01-01"
    end_date: "2024-01-01"
    initial_capital: 1000000
    commission: 0.0003
    slippage: 0.001