# Deprecated: use docker/docker-compose.yml instead
version: "3.8"
services:
  notice:
    image: alpine:3.19
    command: ["sh","-c","echo 'Use docker/docker-compose.yml instead' && sleep 3600"]
    restart: "no"
