version: "3.8"
services:
  app:
    build: .
    container_name: qilin_app
    environment:
      - ENV=production
      - LOG_LEVEL=INFO
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./:/app
    ports:
      - "9090:9090"   # Prometheus metrics
      - "8000:8000"   # API
    command: ["python","main.py","--mode","simulation","--log-level","INFO"]
    depends_on:
      - redis
      - mlflow
  
  redis:
    image: redis:7-alpine
    container_name: qilin_redis
    ports:
      - "6379:6379"
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: qilin_mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: qilin_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: qilin_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mlflow_data:
