
# v2.1 新增: 市场风格元帅配置
# 定义不同市场风格下的策略参数
market_regimes:
  # 默认的“游资混战期”配置
  # 当市场热点散乱，缺乏主线，短线博弈激烈时，元帅会启用此配置
  HOT_MONEY_CHAOS:
    description: "市场热点散乱，缺乏主线，短线博弈激烈，风险较高。"
    
    # 当前风格下的Agent权重, 总和建议为1.0 (风险为负)
    agent_weights:
      zt_quality: 0.15
      leader: 0.15
      auction: 0.12
      money_flow: 0.12
      emotion: 0.10
      risk: -0.10       # 风险Agent作为负向指标或在决策中特殊处理
      technical: 0.08
      position: 0.08
      news: 0.08
      sector: 0.07

    # 当前风格下的风控参数
    risk_parameters:
      max_total_position: 0.6   # 混战期降低总仓位
      default_stop_loss: 0.04   # 更严格的止损
      default_take_profit: 0.08 # 见好就收
      
  # 示例：主升浪时期配置
  # 当市场情绪高涨，主线明确，赚钱效应好时，元帅会启用此配置
  MAIN_WAVE:
    description: "市场情绪高涨，主线明确，赚钱效应好。"
    agent_weights:
      zt_quality: 0.10
      leader: 0.20       # 龙头权重更高
      auction: 0.10
      money_flow: 0.15   # 资金追逐龙头
      emotion: 0.12      # 情绪加成
      risk: -0.05
      technical: 0.08
      position: 0.10
      news: 0.05
      sector: 0.05
    risk_parameters:
      max_total_position: 1.0   # 可以更激进
      default_stop_loss: 0.07   # 容忍更大回撤
      default_take_profit: 0.20 # 让利润奔跑

  # 示例：退潮/冰点期配置
  # 当市场情绪低迷，亏钱效应明显，应以防御为主时，元帅会启用此配置
  RECESSION:
    description: "市场情绪低迷，亏钱效应明显，防御为主。"
    agent_weights:
      zt_quality: 0.05
      leader: 0.05
      auction: 0.10
      money_flow: 0.10
      emotion: 0.10
      risk: -0.25       # 风险权重显著提高
      technical: 0.15   # 更注重技术形态
      position: 0.10
      news: 0.05
      sector: 0.05
    risk_parameters:
      max_total_position: 0.2   # 严格控制仓位
      default_stop_loss: 0.03   # 快速止损
      default_take_profit: 0.05 # 降低盈利预期

# 麒麟量化系统 - 默认配置文件
# 此文件定义系统的默认配置，可被环境变量或命令行参数覆盖

system:
  name: 麒麟量化系统
  version: 1.0.0
  mode: simulation  # simulation/paper/live
  timezone: Asia/Shanghai

data:
  sources:
    - tushare
    - akshare
  cache:
    enabled: true
    ttl: 300  # 秒
    max_size: 1000
  update_interval: 60  # 数据更新间隔（秒）

trading:
  # 股票池
  symbols:
    - "000001"  # 平安银行
    - "000002"  # 万科A
    - "000858"  # 五粮液
    - "002142"  # 宁波银行
    - "300750"  # 宁德时代
    - "600519"  # 贵州茅台
  
  # 持仓管理
  max_positions: 5  # 最大持仓数
  position_size: 0.2  # 单个仓位占比
  
  # 风控参数
  stop_loss: 0.05  # 止损比例
  take_profit: 0.10  # 止盈比例
  max_daily_trades: 20  # 每日最大交易次数
  max_drawdown: 0.15  # 最大回撤限制
  
  # 交易时间
  pre_market_time: "08:55"  # 盘前准备时间
  market_open: "09:30"
  market_close: "15:00"

agents:
  # Agent配置
  parallel: true      # 并行执行
  timeout: 30         # 超时时间（秒）

  # v2.1 新增：决策阈值，用于 IntegratedDecisionAgent
  decision_thresholds:
    strong_buy:
      score: 85       # 得分高于85
      confidence: 0.75  # 且置信度高于0.75
    buy:
      score: 70
      confidence: 0.65
    watch:
      score: 40

database:
  # MongoDB
  mongodb:
    host: localhost
    port: 27017
    database: qilin
    
  # Redis
  redis:
    host: localhost
    port: 6379
    db: 0
    
  # ClickHouse
  clickhouse:
    host: localhost
    port: 8123
    database: qilin

monitoring:
  enabled: true
  
  # Prometheus
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: 15s
    
  # Grafana
  grafana:
    enabled: true
    port: 3000
    
  # 健康检查
  health_check:
    enabled: true
    interval: 60  # 秒
    timeout: 10
    
  # 告警
  alerting:
    enabled: true
    channels:
      - email
      - webhook
    thresholds:
      error_rate: 0.05
      latency_p95: 1000  # ms
      memory_usage: 0.8

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 文件日志
  file:
    enabled: true
    path: logs/qilin.log
    max_size: 100MB
    backup_count: 10
    
  # 控制台日志
  console:
    enabled: true
    colored: true

api:
  host: 0.0.0.0
  port: 8000
  prefix: /api/v1
  docs_enabled: true
  cors_enabled: true
  
  # 限流
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    
  # 认证
  auth:
    enabled: false
    type: jwt
    expiration: 1440  # 分钟

backtest:
  # 回测配置
  initial_capital: 1000000
  commission: 0.0003  # 手续费率
  slippage: 0.001  # 滑点
  benchmark: "000300.SH"  # 沪深300

performance:
  # 性能配置
  max_workers: 4
  async_timeout: 30
  batch_size: 100
  
  # 缓存
  cache:
    strategy_cache: 600  # 策略缓存时间（秒）
    data_cache: 300  # 数据缓存时间
    
  # 优化
  optimization:
    enable_jit: true  # JIT编译
    enable_multiprocessing: true
    enable_gpu: false

# 环境特定配置（会覆盖上述配置）
environments:
  development:
    system:
      mode: simulation
    logging:
      level: DEBUG
      
  production:
    system:
      mode: live
    logging:
      level: WARNING
    monitoring:
      alerting:
        enabled: true