apiVersion: apps/v1
kind: Deployment
metadata:
  name: qilin-business-metrics
  namespace: default
  labels:
    app: qilin-stack
    component: business-metrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qilin-stack
      component: business-metrics
  template:
    metadata:
      labels:
        app: qilin-stack
        component: business-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: metrics-api
          image: qilin-stack/business-metrics:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: business-metrics-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: qilin-business-metrics
  namespace: default
  labels:
    app: qilin-stack
    component: business-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: qilin-stack
    component: business-metrics

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: business-metrics-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qilin-business-metrics
  namespace: default
  labels:
    app: qilin-stack
    component: business-metrics
spec:
  selector:
    matchLabels:
      app: qilin-stack
      component: business-metrics
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
