name: Lint and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements-test.txt ]; then pip install -r tests/requirements-test.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Run unit tests (subset)
        run: |
          pytest -q tests/unit/test_limitup_ensemble_persist.py
        shell: bash

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black isort
        shell: bash

      - name: Black check (non-blocking)
        run: |
          black --version
          black --check models qlib_enhanced factors tradingagents_integration rd_agent || true
        shell: bash

      - name: isort check (non-blocking)
        run: |
          isort --version
          isort --check-only --profile black models qlib_enhanced factors tradingagents_integration rd_agent || true
        shell: bash
